notifications:
  email:
    - letang.jeremy@gmail.com
before_install:
  - sudo apt-get update
install:
  - curl http://static.rust-lang.org/rustup.sh | sudo sh -
  - sudo apt-get install libsndfile1-dev
env:
  - RUST_TEST_TASKS=1
script:
  - cargo build
